name: api

services:
  api:
    container_name: api
    image: ghcr.io/devnergis/api:main
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - api-network
    env_file:
      - .env
    volumes:
      - ${FILE_PATH}:/DATA
      - ./config.toml:/config.toml
    restart: always
    healthcheck:
      disable: false
  
  redis:
    container_name: api-redis
    image: redis/redis-stack-server:latest
    networks:
      - api-network
    env_file:
      - .env
    volumes:
      - ${DB_PATH}:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

networks:
  api-network:
